import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../../styles/Cart.module.css";
import Link from "next/link";
import Cart from "../../components/Cart";

export default function CartPage() {
  return (
    <React.Fragment>
      <Head>
        <title>Cart | Drone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container">
          <h1 className="page-title">Check Yor Order</h1>
          <Cart />
          <div className="actionButtons">
            <Link href="/battery-options" replace>
              <Button
                color="primary"
                variant="contained"
                size="large"
                className="button"
              >
                BACK
              </Button>
            </Link>
            <Link href="/battery-options" replace>
              <Button
                color="secondary"
                variant="contained"
                size="large"
                className="button"
              >
                NEXT
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
