import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../styles/CameraMode.module.css";
import { Button } from "@mui/material";
import Link from "next/link";
import Carousel from "../../components/Carousel.js";
import * as CartService from '../../services/cart';
import { cameraData } from "../../data/cameraData";
import { cartType } from "../../enums";

export default function CameraMode() {

  const cardWidth = 210;
  const cardWidthResponsive = 220;
  const cardMinHeight = 350;
  const columngMargin = 3;

  const [selectedCameraOption, setSelectedCameraOption] = useState(0)

  useEffect(() => {
    setSelectedCameraOption(CartService.getCameraType())
  }, [])


  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="page-title">Choose Camera Mode</h1>
        <Carousel
          cards={cameraData}
          minHeight={cardMinHeight}
          width={cardWidth}
          responsiveWidth={cardWidthResponsive}
          columnMr={columngMargin}
          preSelected={selectedCameraOption}
          optionType={cartType.CAMERA}
        />
        <div className="actionButtons">
          <Link href="/choose-style" replace>
            <Button
              color="primary"
              variant="contained"
              size="large"
              className="button"
            >
              BACK
            </Button>
          </Link>
          <Link href="/battery-options" replace>
            <Button
              color="secondary"
              variant="contained"
              size="large"
              className="button"
            >
              NEXT
            </Button>
          </Link>
        </div>
      </main>
    </React.Fragment>
  );
}
