import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../../styles/ChooseStyle.module.css";
import { DroneVariant } from "../../components/UI/DroneVariant";
import CheckIcon from "@mui/icons-material/Check";
import Link from "next/link";

export default function Home() {
  const [selectedDrone, setSelectedDrone] = useState("");

  const selectDrone = (variant) => {
    if (variant === "black") setSelectedDrone("black");
    else setSelectedDrone("white");
  };

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <h1 className="page-title">Choose Your Style</h1>
          <div className={styles.variantContainer}>
            <DroneVariant
              onClick={() => selectDrone("black")}
              backgroundColor="#0D0D0D"
              color="#EDEDED"
              selected={selectedDrone === "black"}
            >
              <div className="selected" style={{ backgroundColor: "#3CB850" }}>
                <CheckIcon sx={{ backgroundColor: "#3CB850 !important" }} />
              </div>
              <div className={styles.blackDroneImageContainer}>
                <Image
                  className={styles.blackDroneImage}
                  src="/images/black-edited-final.png"
                  layout="fill"
                />
              </div>
            </DroneVariant>
            <DroneVariant
              onClick={() => selectDrone("white")}
              backgroundColor="#EDEDED"
              color="#2F2F2F"
              selected={selectedDrone === "white"}
            >
              <div className="selected" style={{ backgroundColor: "#3CB850" }}>
                <CheckIcon sx={{ backgroundColor: "#3CB850 !important" }} />
              </div>
              <div className={styles.whiteDroneImageContainer}>
                <Image
                  className={styles.whiteDroneImage}
                  src="/images/White-edited-lines.png"
                  layout="fill"
                />
              </div>
            </DroneVariant>
          </div>
          <div className="actionButtons">
            <Link href="/" replace>
              <Button
                color="primary"
                variant="contained"
                size="large"
                className="button"
              >
                EXIT
              </Button>
            </Link>
            <Link href="/camera-mode" replace>
              <Button
                color="secondary"
                variant="contained"
                size="large"
                className="button"
              >
                NEXT
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
