import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import styles from "../../styles/ChooseStyle.module.css";
import { DroneVariant } from "../../components/UI/DroneVariant";
import CheckIcon from "@mui/icons-material/Check";
import Link from "next/link";
import { droneType } from '../../enums/index'
import * as CartService from '../../services/cart'

export default function Home() {

  const [selectedDrone, setSelectedDrone] = useState(0);
  
  const [cart, setCart] = useState(CartService.getCart());

  const selectDroneHandler = (drone) => {

    setSelectedDrone(drone)

    const newCartState = CartService.setDroneType(drone)

    setCart(newCartState)
  }

  useEffect(() => {
    const droneFromCart = CartService.getDroneType()

    setSelectedDrone(droneFromCart)
  }, [])


  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <h1 className="page-title">Choose Your Style</h1>
          <div className={styles.variantContainer}>
            <DroneVariant
              onClick={() => selectDroneHandler(droneType.BLACK)}
              backgroundColor="#0D0D0D"
              color="#EDEDED"
              selected={selectedDrone === droneType.BLACK}
            >
              <div className="selected" style={{ backgroundColor: "#3CB850" }}>
                <CheckIcon sx={{ backgroundColor: "#3CB850 !important" }} />
              </div>
              <div className={styles.blackDroneImageContainer}>
                <Image
                  className={styles.blackDroneImage}
                  src="/images/black-edited-final.png"
                  layout="fill"
                />
              </div>
            </DroneVariant>
            <DroneVariant
              onClick={() => selectDroneHandler(droneType.WHITE)}
              backgroundColor="#EDEDED"
              color="#2F2F2F"
              selected={selectedDrone === droneType.WHITE}
            >
              <div className="selected" style={{ backgroundColor: "#3CB850" }}>
                <CheckIcon sx={{ backgroundColor: "#3CB850 !important" }} />
              </div>
              <div className={styles.whiteDroneImageContainer}>
                <Image
                  className={styles.whiteDroneImage}
                  src="/images/White-edited-lines.png"
                  layout="fill"
                />
              </div>
            </DroneVariant>
          </div>
          <div className="actionButtons">
            <Link href="/" replace>
              <Button
                color="primary"
                variant="contained"
                size="large"
                className="button"
              >
                EXIT
              </Button>
            </Link>
            <Link href="/camera-mode" replace>
              <Button
                color="secondary"
                variant="contained"
                size="large"
                className="button"
              >
                NEXT
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
