import { Box, Button, Divider, Paper } from "@mui/material";
import { minHeight } from "@mui/system";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { PaymentOptionSelection } from "../../components/UI/PaymentOptionSelection";
import styles from "../../styles/PaymentMethod.module.css";
import { PaymentOption } from "../../enums";

import * as PaymentService from '../../services/paymentService'

export default function PaymentMethod() {

    const [paymentOption, setPaymentOption] = useState(0)

    const router = useRouter()

    const handleNext = () => {
        if (paymentOption === 0) return
        PaymentService.setPaymentMethod(paymentOption)
        nextPageHandler()
    }

    const nextPageHandler = () => {
        switch (paymentOption) {
            case PaymentOption.CREDIT_CART:
                router.push('/cc-payment')
                break;
            case PaymentOption.PAY_PAL:
                router.push('/paypal-payment')
                break;
            case PaymentOption.CRYPTO:
                router.push('/crypto-payment')
                break;
        }
    }

    return (
        <React.Fragment>
            <Head>
                <title>Choose Payment Method | Drone App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className="container" style={{ minHeight: '100vh', minWidth: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Paper elevation={3} className={styles.paymentContainer}>
                        <h3>Select Payment Method</h3>
                        <Divider sx={{ marginBottom: '1.6rem' }} />
                        <Box className={styles.options}>
                            <PaymentOptionSelection
                                selected={paymentOption == PaymentOption.CREDIT_CART}
                                onClick={() => setPaymentOption(PaymentOption.CREDIT_CART)}>
                                <div className="circle">
                                    <div></div>
                                </div>
                                <Box className={styles.paymentOption}>
                                    <h4>Credit Card Payment</h4>
                                    <Box className={styles.icons}>
                                        <Box className={styles.rectangleIconContainer}>
                                            <Image
                                                src={`/images/Free-Credit-Card-Icons-PSD-1.png`}
                                                className={styles.rectangleIcon}
                                                layout="fill"
                                            />
                                        </Box>
                                        <Box className={styles.rectangleIconContainer}>
                                            <Image
                                                src={`/images/master.png`}
                                                className={styles.rectangleIcon}
                                                layout="fill"
                                            />
                                        </Box>
                                        <Box className={styles.rectangleIconContainer}>
                                            <Image
                                                src={`/images/discover.png`}
                                                className={styles.rectangleIcon}
                                                layout="fill"
                                            />
                                        </Box>
                                    </Box>
                                </Box>
                            </PaymentOptionSelection>
                            <PaymentOptionSelection
                                selected={paymentOption == PaymentOption.PAY_PAL}
                                onClick={() => setPaymentOption(PaymentOption.PAY_PAL)}>
                                <div className="circle">
                                    <div></div>
                                </div>
                                <Box className={styles.paymentOption}>
                                    <h4>PaylPal Payment</h4>
                                    <Box className={styles.icons}>
                                        <Box className={styles.wideIconContainer}>
                                            <Image
                                                src={`/images/pay-pal.png`}
                                                className={styles.wideIcon}
                                                layout="fill"
                                            />
                                        </Box>
                                    </Box>
                                </Box>
                            </PaymentOptionSelection>
                            <PaymentOptionSelection
                                selected={paymentOption == PaymentOption.CRYPTO}
                                onClick={() => setPaymentOption(PaymentOption.CRYPTO)}>
                                <div className="circle">
                                    <div></div>
                                </div>
                                <Box className={styles.paymentOption}>
                                    <h4>Crypto Currency</h4>
                                    <Box className={styles.icons}>
                                        <Box className={styles.icons}>
                                            <Box className={styles.rectangleIconContainer}>
                                                <Image
                                                    src={`/images/bitcoin.png`}
                                                    className={styles.rectangleIcon}
                                                    layout="fill"
                                                />
                                            </Box>
                                            <Box className={styles.rectangleIconContainer}>
                                                <Image
                                                    src={`/images/ethereum.png`}
                                                    className={styles.rectangleIcon}
                                                    layout="fill"
                                                />
                                            </Box>
                                            <Box className={styles.wideIconContainer}>
                                                <Image
                                                    src={`/images/litecoin.png`}
                                                    className={styles.wideIcon}
                                                    layout="fill"
                                                />
                                            </Box>
                                        </Box>
                                    </Box>
                                </Box>
                            </PaymentOptionSelection>
                        </Box>
                        <Divider />
                        <div className="actionButtons" style={{ paddingTop: '2rem', paddingBottom: '1rem' }}>
                            <Link href="/checkout" replace>
                                <Button
                                    color="secondary"
                                    variant="contained"
                                    size="medium"
                                    className="button"
                                >
                                    CANCEL ORDER
                                </Button>
                            </Link>

                            <Button
                                color="primary"
                                variant="contained"
                                size="medium"
                                className="button"
                                disabled={paymentOption === 0}
                                onClick={handleNext}
                            >
                                SELECT PAYMENT
                            </Button>
                        </div>
                    </Paper>
                </div>
            </main>
        </React.Fragment >
    );
}
