import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Cart from "../../components/Cart";
import CheckoutComponent from "../../components/Chekout";
import Footer from "../../components/Home/Footer";
import styles from "../../styles/Checkout.module.css";

export default function CheckoutPage() {

    return (
        <React.Fragment>
            <Head>
                <title>Choose Battery Option | Drone App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <ToastContainer />
                <div className={styles.leftPolyImageContainer}>
                    <Image
                        src={`/images/polygon-side.png`}
                        className={styles.leftPolyImage}
                        layout="fill"
                    />
                </div>
                <div className={styles.rightPolyImageContainer}>
                    <Image
                        src={`/images/Polygon 3.png`}
                        className={styles.rightPolyImage}
                        layout="fill"
                    />
                </div>
                <div className="container">
                    <h1 className="page-title">
                        Checkout
                    </h1>
                    <section className={styles.mainGrid}>
                        <CheckoutComponent />
                        <div className={styles.cartGrid}>
                            <Cart />
                        </div>
                    </section>
                </div>
            </main>
            <Footer/>
        </React.Fragment>
    )
}