import { Box, Fab } from "@mui/material";
import Head from "next/head";
import React from "react";
import { useSelector } from "react-redux";
import Header from "../components/Header";
import SideBar from "../components/Header/SideBar";
import BlackOrWhite from "../components/Home/BlackOrWhite";
import ByTracking from "../components/Home/ByTracking";
import Camera from "../components/Home/Camera";
import Compatible from "../components/Home/Compatible";
import Controller from "../components/Home/Controller";
import DroneApp from "../components/Home/DroneApp";
import Footer from "../components/Home/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {


  const sidebarOpen = useSelector(state => state.sideBarOpen)

  return (
    <React.Fragment >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
      <SideBar sidebarOpen={sidebarOpen} />
      {!sidebarOpen &&
        <>

          <Header />
          <main className={styles.main}>


            <Camera />
            <Controller />
            <Compatible />
            <ByTracking />
            <BlackOrWhite />
            <DroneApp />
            <Footer />
          </main>

        </>
      }

    </React.Fragment>
  );
}
